//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontDeskApp.Models
{
    using FrontDeskApp.BaseValidatorObject;
    using System;
    using System.Collections.Generic;
    
    public partial class box
    {
        public box()
        {
            this.customerrecord = new HashSet<customerrecord>();
        }
    
        public int boxid { get; set; }
        public int boxtypeid { get; set; }
        public int boxnumber { get; set; }
        public bool isavailable { get; set; }

        public BaseValidator Validation { get; set; }

        public virtual boxtype boxtype { get; set; }
        public virtual ICollection<customerrecord> customerrecord { get; set; }
    }
}
