//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontDeskApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class boxtype
    {
        public boxtype()
        {
            this.box = new HashSet<box>();
        }
    
        public int boxtypeid { get; set; }
        public string boxtype1 { get; set; }
    
        public virtual ICollection<box> box { get; set; }
    }
}
