//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontDeskApp.Models
{
    using FrontDeskApp.BaseValidatorObject;
    using System;
    using System.Collections.Generic;
    
    public partial class customer
    {
        public customer()
        {
            this.customerrecord = new HashSet<customerrecord>();
        }
    
        public int customerid { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        public string phonenumber { get; set; }

        public BaseValidator Validation { get; set; }

        public virtual ICollection<customerrecord> customerrecord { get; set; }
    }
}
